// Every word the admin page shows, in English and in Ukrainian. The page
// picks one dictionary by the switch in its header; a key missing from one
// language falls back to English, then to the key itself -- and the test
// makes sure no key is missing from either.
window.OZ_STR = {
  en: {
    title: 'OpenZone Storage',
    nav_boxes: 'Boxes', nav_shelf: 'Shelf', nav_find: 'Find', nav_player: 'Player', nav_health: 'Health',
    your_name: 'Your name for the log', sign_in: 'Sign in with Discord', sign_out: 'Sign out', signed_in_as: 'Signed in as', sign_in_first: 'Sign in to see the boxes.',
    loading: 'Loading…', nothing: 'Nothing here', error: 'Error', search: 'Search', done: 'Done.', confirm: 'Confirm', cancel: 'Cancel', close: 'Close',
    id: 'Id', cls: 'Class', status: 'Status', items: 'Items', roots: 'Roots', pos: 'Position', placed_by: 'Placed by', placed_at: 'Placed at', last_seen: 'Last contact',
    version: 'Version', versions: 'Versions', stamp: 'Stamp', source: 'Source', note: 'Note', events: 'Events', when: 'When', kind: 'Event', who: 'Who', qty: 'Qty', cell: 'Cell', slot: 'Slot', health: 'Health', admin: 'Admin', actions: 'Actions', box: 'Box', current: 'current', classes: 'Classes', uid: 'Steam64',
    st_closed: 'closed', st_open: 'open', st_removed: 'removed',
    size_small: 'small, 10×5', size_medium: 'medium, 10×10', size_large: 'large, 10×15',
    grid: 'Grid', tree: 'Contents', filter: 'Filter by class', unplaced: 'Waiting for a free cell', in_slots: 'In the slots', has_state: 'carries mod state', history: 'History',
    give: 'Give an item', give_class: 'Class', give_qty: 'Quantity (0 = default)', empty: 'Empty the box', shelve: 'To the shelf', move: 'Move', move_to: 'Id of the box to move into', edit: 'Edit',
    edit_qty: 'Quantity (empty = keep, 0 = default)', edit_health: 'Health (empty = keep, -1 = class default)', reset: 'Reset the mod state of the whole item tree',
    rollback: 'Roll back', compare: 'Compare with current', gone: 'Disappears', came: 'Appears', same: 'The same classes as the current version.', rollback_to: 'Roll back to this version',
    takes_effect: 'It takes effect at the next open of the box.', closed_only: 'Only a closed box can be changed here.',
    shelf_return: 'Return', shelf_discard: 'Throw away', reason: 'Reason', from_version: 'From version', parked_at: 'Parked at',
    last_taken: 'Last taken by', nobody_took: 'Nobody has taken this class yet.',
    xchg: 'Exchange directory', configured: 'configured', not_configured: 'not configured', servers: 'Game servers', last_poll: 'last poll', no_servers: 'No game server has polled yet.',
    open_boxes: 'Boxes SQL believes open', db_size: 'Database size', keep: 'The next clean-up removes', keep_versions: 'versions', keep_events: 'events', auth: 'Sign-in', auth_discord: 'Discord', auth_none: 'none, loopback only',
    c_rollback: 'Roll box {id} back to version {v}?', c_empty: 'Empty box {id}?', c_shelve: 'Put {type} from box {id} on the shelf?', c_move: 'Move {type} from {id} into {to}?',
    c_edit: 'Change {type} in box {id}?', c_edit_reset: 'Change {type} in box {id} and reset the mod state of its whole item tree?',
    c_return: 'Return {type} to box {id}?', c_discard: 'Throw {type} away for good?', c_give: 'Give {type} ×{qty} to box {id}?',
    new_version: 'New version {v}.', two_versions: 'Versions {a} and {b}.',
    live_report: 'Report from the game', live_close: 'Close now', live_remove: 'Remove from the world',
    live_sent: 'Sent to the game, waiting for the answer…', live_answer: 'The game answered:',
    live_silent: 'No answer within 12 s; the game polls the bridge every few seconds — try again in a moment.',
    c_close: 'Close box {id} now and drop its viewers?', c_remove: 'Remove box {id} from the world? Its history stays in the database.',
  },
  uk: {
    title: 'Сховище OpenZone',
    nav_boxes: 'Ящики', nav_shelf: 'Полиця', nav_find: 'Пошук', nav_player: 'Гравець', nav_health: 'Стан',
    your_name: 'Ваше ім’я для журналу', sign_in: 'Увійти через Discord', sign_out: 'Вийти', signed_in_as: 'Ви увійшли як', sign_in_first: 'Увійдіть, щоб побачити ящики.',
    loading: 'Завантаження…', nothing: 'Тут порожньо', error: 'Помилка', search: 'Шукати', done: 'Готово.', confirm: 'Підтвердити', cancel: 'Скасувати', close: 'Закрити',
    id: 'Id', cls: 'Клас', status: 'Стан', items: 'Предметів', roots: 'Коренів', pos: 'Позиція', placed_by: 'Поставив', placed_at: 'Поставлено', last_seen: 'Останній контакт',
    version: 'Версія', versions: 'Версії', stamp: 'Штамп', source: 'Джерело', note: 'Примітка', events: 'Події', when: 'Коли', kind: 'Подія', who: 'Хто', qty: 'К-сть', cell: 'Комірка', slot: 'Слот', health: 'Здоров’я', admin: 'Адмін', actions: 'Дії', box: 'Ящик', current: 'поточна', classes: 'Класи', uid: 'Steam64',
    st_closed: 'зачинений', st_open: 'відкритий', st_removed: 'прибраний',
    size_small: 'малий, 10×5', size_medium: 'середній, 10×10', size_large: 'великий, 10×15',
    grid: 'Сітка', tree: 'Вміст', filter: 'Фільтр за класом', unplaced: 'Чекають вільної комірки', in_slots: 'У слотах', has_state: 'має стан мода', history: 'Історія',
    give: 'Видати предмет', give_class: 'Клас', give_qty: 'Кількість (0 = типова)', empty: 'Спорожнити ящик', shelve: 'На полицю', move: 'Перенести', move_to: 'Id ящика, куди перенести', edit: 'Змінити',
    edit_qty: 'Кількість (порожньо = лишити, 0 = типова)', edit_health: 'Здоров’я (порожньо = лишити, -1 = типове для класу)', reset: 'Скинути стан мода всього дерева предмета',
    rollback: 'Відкотити', compare: 'Порівняти з поточною', gone: 'Зникне', came: 'З’явиться', same: 'Ті самі класи, що й у поточній версії.', rollback_to: 'Відкотити до цієї версії',
    takes_effect: 'Набуде чинності при наступному відкритті ящика.', closed_only: 'Змінювати тут можна лише зачинений ящик.',
    shelf_return: 'Повернути', shelf_discard: 'Викинути', reason: 'Причина', from_version: 'З версії', parked_at: 'Припарковано',
    last_taken: 'Останнім брав', nobody_took: 'Цей клас ще ніхто не брав.',
    xchg: 'Каталог обміну', configured: 'налаштовано', not_configured: 'не налаштовано', servers: 'Ігрові сервери', last_poll: 'останній запит', no_servers: 'Жоден ігровий сервер ще не звертався.',
    open_boxes: 'Ящики, які SQL вважає відкритими', db_size: 'Розмір бази', keep: 'Наступне чищення видалить', keep_versions: 'версій', keep_events: 'подій', auth: 'Вхід', auth_discord: 'Discord', auth_none: 'без входу, лише локально',
    c_rollback: 'Відкотити ящик {id} до версії {v}?', c_empty: 'Спорожнити ящик {id}?', c_shelve: 'Прибрати {type} з ящика {id} на полицю?', c_move: 'Перенести {type} з {id} до {to}?',
    c_edit: 'Змінити {type} у ящику {id}?', c_edit_reset: 'Змінити {type} у ящику {id} і скинути стан мода всього його дерева предметів?',
    c_return: 'Повернути {type} до ящика {id}?', c_discard: 'Викинути {type} назавжди?', c_give: 'Видати {type} ×{qty} до ящика {id}?',
    new_version: 'Нова версія {v}.', two_versions: 'Версії {a} та {b}.',
    live_report: 'Звіт з гри', live_close: 'Зачинити зараз', live_remove: 'Прибрати зі світу',
    live_sent: 'Надіслано в гру, чекаю відповіді…', live_answer: 'Гра відповіла:',
    live_silent: 'Відповіді немає 12 с; гра опитує міст раз на кілька секунд — спробуйте за хвилину.',
    c_close: 'Зачинити ящик {id} зараз і відключити глядачів?', c_remove: 'Прибрати ящик {id} зі світу? Його історія лишається в базі.',
  },
};
